name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  bootstrap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install workspace
        run: pnpm -w install

  server-build:
    runs-on: ubuntu-latest
    needs: [bootstrap]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install workspace
        run: pnpm -w install
      - name: Build server
        run: pnpm --filter @giggle/server run build

  mobile-lint:
    runs-on: ubuntu-latest
    needs: [bootstrap]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install workspace
        run: pnpm -w install
      - name: Mobile lint
        run: pnpm --filter @giggle/mobile run lint
      - name: Mobile typecheck
        run: pnpm --filter @giggle/mobile exec tsc --noEmit || true
